---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/Berlin"

  # Daily: Check minor and patch updates
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
    # https://github.com/dependabot/dependabot-core/issues/5226#issuecomment-1179434437
    versioning-strategy: increase
    groups:
      patch-dependencies:
        update-types:
          - "patch"
        patterns:
          - "*"
